const Images = {
  matThu: require('../assets/images/mat-thu.png'),
  semaphore: require('../assets/images/semaphore.png'),
  scoutBoy: require('../assets/images/scoutboy.png'),
  morse: require('../assets/images/morse.png'),
  background: require('../assets/images/background.jpeg'),
  bgMorse: require('../assets/images/bg-morse.jpeg'),
  bgSemaphore: require('../assets/images/bg-semaphore.jpeg'),
  bgMatthu: require('../assets/images/bg-matthu.jpeg'),
  bgScout: require('../assets/images/bg-scout.jpeg'),

  alphabet: {
    A: '../assets/alphabetSemaphore/A.png',
    B: '../assets/alphabetSemaphore/B.png',
    C: '../assets/alphabetSemaphore/C.png',
    D: '../assets/alphabetSemaphore/D.png',
    E: '../assets/alphabetSemaphore/E.png',
    F: '../assets/alphabetSemaphore/F.png',
    G: '../assets/alphabetSemaphore/G.png',
    H: '../assets/alphabetSemaphore/H.png',
    I: '../assets/alphabetSemaphore/I.png',
    J: '../assets/alphabetSemaphore/J.png',
    K: '../assets/alphabetSemaphore/K.png',
    L: '../assets/alphabetSemaphore/L.png',
    M: '../assets/alphabetSemaphore/M.png',
    N: '../assets/alphabetSemaphore/N.png',
    O: '../assets/alphabetSemaphore/O.png',
    P: '../assets/alphabetSemaphore/P.png',
    Q: '../assets/alphabetSemaphore/Q.png',
    R: '../assets/alphabetSemaphore/R.png',
    S: '../assets/alphabetSemaphore/S.png',
    T: '../assets/alphabetSemaphore/T.png',
    U: '../assets/alphabetSemaphore/U.png',
    V: '../assets/alphabetSemaphore/V.png',
    W: '../assets/alphabetSemaphore/W.png',
    X: '../assets/alphabetSemaphore/X.png',
    Y: '../assets/alphabetSemaphore/Y.png',
    Z: '../assets/alphabetSemaphore/Z.png',
  },
};

export default Images;
