import Images from '../themes/Images';

export enum typeAlphabet {
  'A' = Images.alphabet.A,
  'B' = Images.alphabet.B,
  'C' = Images.alphabet.C,
  'D' = Images.alphabet.D,
  'E' = Images.alphabet.E,
  'F' = Images.alphabet.F,
  'G' = Images.alphabet.G,
  'H' = Images.alphabet.H,
  'I' = Images.alphabet.I,
  'J' = Images.alphabet.J,
  'K' = Images.alphabet.K,
  'L' = Images.alphabet.L,
  'M' = Images.alphabet.M,
  'N' = Images.alphabet.N,
  'O' = Images.alphabet.O,
  'P' = Images.alphabet.P,
  'Q' = Images.alphabet.Q,
  'R' = Images.alphabet.R,
  'S' = Images.alphabet.S,
  'T' = Images.alphabet.T,
  'U' = Images.alphabet.U,
  'V' = Images.alphabet.V,
  'W' = Images.alphabet.W,
  'X' = Images.alphabet.X,
  'Y' = Images.alphabet.Y,
  'Z' = Images.alphabet.Z,
}
